# Generated by Django 4.1.2 on 2022-11-09 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branchs',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('details', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('progress', models.CharField(blank=True, max_length=200, null=True)),
                ('task', models.CharField(blank=True, max_length=200, null=True)),
                ('tempc', models.CharField(blank=True, max_length=100, null=True)),
                ('tempp', models.CharField(blank=True, max_length=200, null=True)),
                ('tempt', models.CharField(blank=True, max_length=200, null=True)),
                ('estatus', models.CharField(blank=True, max_length=200, null=True)),
                ('completed', models.CharField(blank=True, max_length=100, null=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo.branch')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo.department')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=10)),
                ('stime', models.CharField(blank=True, max_length=10, null=True)),
                ('etime', models.CharField(blank=True, max_length=10, null=True)),
                ('sdate', models.CharField(blank=True, max_length=20, null=True)),
                ('day', models.CharField(max_length=20, null=True)),
                ('fdate', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'Strategy',
                'verbose_name_plural': 'Strategys',
            },
        ),
        migrations.CreateModel(
            name='Thought',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desce', models.CharField(blank=True, max_length=500, null=True)),
                ('typ', models.CharField(blank=True, max_length=100, null=True)),
                ('descm', models.CharField(blank=True, max_length=500, null=True)),
                ('img', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Thought',
                'verbose_name_plural': 'Thoughts',
            },
        ),
        migrations.CreateModel(
            name='Strgtask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliv', models.CharField(blank=True, max_length=30, null=True)),
                ('howmes', models.CharField(blank=True, max_length=20, null=True)),
                ('wgt', models.CharField(max_length=250)),
                ('base', models.CharField(blank=True, max_length=200, null=True)),
                ('goal', models.CharField(blank=True, max_length=200, null=True)),
                ('hilo', models.CharField(blank=True, max_length=200, null=True)),
                ('result', models.CharField(blank=True, max_length=200, null=True)),
                ('empid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo.employee')),
                ('sid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo.strategy')),
            ],
            options={
                'verbose_name': 'Strgtask',
                'verbose_name_plural': 'Strgtasks',
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=10)),
                ('pid', models.CharField(max_length=10)),
                ('stime', models.CharField(blank=True, max_length=10, null=True)),
                ('etime', models.CharField(blank=True, max_length=10, null=True)),
                ('sdate', models.CharField(blank=True, max_length=20, null=True)),
                ('day', models.CharField(max_length=20, null=True)),
                ('fdate', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('thought', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo.thought')),
            ],
            options={
                'verbose_name': 'Operation',
                'verbose_name_plural': 'Operations',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('tasks', models.CharField(max_length=250)),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
                ('empid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo.employee')),
                ('opsid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo.operation')),
                ('sid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo.strategy')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
            },
        ),
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.CharField(blank=True, max_length=20, null=True)),
                ('date', models.CharField(blank=True, max_length=20, null=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo.job')),
            ],
            options={
                'verbose_name': 'Count',
                'verbose_name_plural': 'Counts',
            },
        ),
    ]
