# Generated by Django 4.1.2 on 2022-11-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thought',
            name='date',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
