# Generated by Django 4.1.2 on 2022-11-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_alter_thought_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='thought',
            name='day',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
