# Generated by Django 4.1.2 on 2022-11-19 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_estatus_employee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='empid',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
