# Generated by Django 4.1.2 on 2022-11-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_alter_job_empid'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='quantity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='remark',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
